### ISSUE TITLE
Installation on Mac OSX failed via brew.sh

### ISSUE THREAD

**Issue by ookangzheng** [cloudflare/quiche#1008]
Error log

```
❯ brew install --HEAD -s curl.rb
Error: Failed to load cask: curl.rb
Cask 'curl' is unreadable: wrong constant name #<Class:0x00007fcce090dfa8>
Warning: Treating curl.rb as a formula.
==> Cloning https://github.com/curl/curl.git
Updating /Users/loll/Library/Caches/Homebrew/curl--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 02dfce183 scripts: Fix typo in release-notes instructions
==> ./buildconf
==> git clone --recursive https://github.com/cloudflare/quiche
==> cargo build --release --features pkg-config-meta,qlog
==> ./configure --prefix=/usr/local/Cellar/curl/HEAD-02dfce1 --with-secure-trans
Last 15 lines from /Users/loll/Library/Logs/Homebrew/curl/04.configure:
checking for libnghttp2 options with pkg-config... found
configure: -l is -lnghttp2
configure: -I is -I/usr/local/Cellar/nghttp2/1.43.0/include
configure: -L is -L/usr/local/Cellar/nghttp2/1.43.0/lib
checking for nghttp2_session_set_local_window_size in -lnghttp2... yes
checking for nghttp2/nghttp2.h... yes
checking for pkg-config... (cached) /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking for libngtcp2 options with pkg-config... no
checking for pkg-config... (cached) /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking for quiche options with pkg-config... found
configure: -l is -lquiche
configure: -I is -I/private/tmp/curl-20210712-12162-im3znt/quiche/include
configure: -L is -L/private/tmp/curl-20210712-12162-im3znt/quiche/target/release
checking for quiche_connect in -lquiche... no
configure: error: couldn't use quiche

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
	24: from /usr/local/Homebrew/Library/Homebrew/build.rb:133:in `install'
	23: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	22: from /usr/local/Homebrew/Library/Homebrew/build.rb:138:in `block in install'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1260:in `brew'
	20: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2363:in `stage'
	19: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	16: from /usr/local/Homebrew/Library/Homebrew/resource.rb:199:in `mktemp'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	13: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	12: from /usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	11: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
	10: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:110:in `chdir'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2383:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2384:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1267:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:178:in `block (2 levels) in install'
	 3: from /Users/loll/curl.rb:70:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2154:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2154:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2218:in `block in system': Failed executing: ./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/usr/local/Cellar/curl/HEAD-02dfce1 --with-secure-transport --without-ca-bundle --without-ca-path --with-ssl=/private/tmp/curl-20210712-12162-im3znt/quiche/deps/boringssl/src --with-quiche=/private/tmp/curl-20210712-12162-im3znt/quiche/target/release --enable-alt-svc (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:509:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:455:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:459:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:60:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
```

**Comment by junhochoi** [comment]
Can you try https://github.com/cloudflare/homebrew-cloudflare/pull/29 ??

**Comment by ookangzheng** [comment]
It works.

Thanks for your help
