### ISSUE TITLE
panic when using `connect-to` in client

### ISSUE THREAD

**Issue by moderation** [cloudflare/quiche#1081]
quiche panics when trying to use the `connect-to` value in the client

https://github.com/cloudflare/quiche/blob/master/tools/apps/src/args.rs#L289-L293

`env RUST_BACKTRACE=1 /home/username/Library/rust/quiche/tools/apps/target/x86_64-unknown-linux-musl/release/quiche-client --connect-to='www.google.com' https://www.google.com/`
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrParseError(())', /home/username/Library/rust/quiche/tools/apps/src/client.rs:68:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1299:23
   4: quiche_apps::client::connect
             at ./Library/rust/quiche/tools/apps/src/client.rs:68:9
   5: quiche_client::main
             at ./Library/rust/quiche/tools/apps/src/bin/quiche-client.rs:43:11
   6: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Doesn't seem to matter what the value of `connect-to` is. Any ideas?

**Comment by LPardue** [comment]
this argument takes an IP address not a hostname.
