### ISSUE TITLE
quiche-client panics on EINTR

### ISSUE THREAD

**Issue by jyn514** [cloudflare/quiche#1248]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 4, kind: Interrupted, message: "Interrupted system call" }', /home/jnelson/work/quiche/apps/src/client.rs:213:52
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/core/src/result.rs:1078:23
   4: quiche_apps::client::connect
             at /home/jnelson/work/quiche/apps/src/client.rs:213:13
   5: quiche_client::main
             at /home/jnelson/work/quiche/apps/src/bin/quiche-client.rs:43:11
   6: core::ops::function::FnOnce::call_once
             at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I think normally the right behavior is just to retry the system call?
https://github.com/cloudflare/quiche/blob/a7ab6dd0363b83b09039e166a5dae18fc75bec52/apps/src/client.rs#L213

**Comment by LPardue** [comment]
probably, yeah
