### ISSUE TITLE
 recv failed: BufferTooShort

### ISSUE THREAD

**Issue by piano-man** [cloudflare/quiche#374]
Running the client command "**_cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-client -- https://quic.tech:8443/_**"  causes this error :- 

**_Finished dev [unoptimized + debuginfo] target(s) in 0.18s 
                                                                                                                                                                                    Running `tools/apps/target/debug/quiche-client 'https://quic.tech:8443/'`
                                                                                                                                                               [2020-02-25T10:30:39.260818300Z ERROR quiche_client] recv failed: BufferTooShort
                                                                                                                                                             thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TransportError(StreamLimit)', src/libcore/result.rs:1188:5_**  

This started happening yesterday onwards . It was working fine before that.

**Comment by junhochoi** [comment]
It works for me using today's master. Can you try again? If you still have the issue please post the log with RUST_LOG=trace
```
$ cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-client -- https://quic.tech:8443/
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `tools/apps/target/debug/quiche-client 'https://quic.tech:8443/'`
<!DOCTYPE html>

<html>
<head>
...
```

**Comment by piano-man** [comment]
This is what I'm getting :- 
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s    
                                                                                                                                                                                 Running `tools/apps/target/debug/quiche-client 'https://quic.tech:8443/'`
                                                                                                                                                               [2020-02-26T11:19:04.311590600Z TRACE mio::poll] registering with poller
                                                                                                                                                                     [2020-02-26T11:19:04.402157400Z TRACE quiche::cc] Initializing congestion control: Reno
                                                                                                                                                      [2020-02-26T11:19:04.402973400Z INFO  quiche_client] connecting to 185.92.221.97:8443 from 134.96.235.133:63723 with scid a90df470b71e1a33c9ed1658f23f5279c640c4b5
                                                                           [2020-02-26T11:19:04.403597100Z TRACE quiche::tls] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tls write message lvl=Initial len=512
                                                                                                            [2020-02-26T11:19:04.403989200Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tx pkt Initial version=babababa dcid=10101df24b578c5807fbe93484c79b58 scid=a90df470b71e1a33c9ed1658f23f5279c640c4b5 len=1153 pn=0                     [2020-02-26T11:19:04.404349600Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tx frm CRYPTO off=0 len=512                                                                                                                           [2020-02-26T11:19:04.404604300Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tx frm PADDING len=621                                                                                                                                [2020-02-26T11:19:04.405007500Z TRACE quiche::recovery] a90df470b71e1a33c9ed1658f23f5279c640c4b5 timer=998.3137ms latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=14520 ssthresh=18446744073709551615 bytes_in_flight=1200
                                                                                                                                                                                                        [2020-02-26T11:19:04.405789900Z DEBUG quiche_client] written 1200                                                                                                                                                                            [2020-02-26T11:19:04.428037800Z DEBUG quiche_client] got 55 bytes                                                                                                                                                                            [2020-02-26T11:19:04.428695500Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx pkt VersionNegotiation version=0 dcid=a90df470b71e1a33c9ed1658f23f5279c640c4b5 scid=10101df24b578c5807fbe93484c79b58 versions=[ff00001b, ff000018, ff000017]                                                                                                                                                                                                                                    [2020-02-26T11:19:04.429210000Z DEBUG quiche_client] done reading                                                                                                                                                                            [2020-02-26T11:19:04.429790200Z TRACE quiche::tls] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tls write message lvl=Initial len=512                                                                                                            [2020-02-26T11:19:04.430159900Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tx pkt Initial version=ff000018 dcid=10101df24b578c5807fbe93484c79b58 scid=a90df470b71e1a33c9ed1658f23f5279c640c4b5 len=1153 pn=1                     [2020-02-26T11:19:04.430543000Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tx frm CRYPTO off=0 len=512
                                                                                                                           [2020-02-26T11:19:04.430837300Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tx frm PADDING len=62
                                                                                                                                [2020-02-26T11:19:04.431241500Z TRACE quiche::recovery] a90df470b71e1a33c9ed1658f23f5279c640c4b5 timer=998.2423ms latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=14520 ssthresh=18446744073709551615 bytes_in_flight=1200
                                                                                                                                                                                                        [2020-02-26T11:19:04.431947700Z DEBUG quiche_client] written 1200
                                                                                                                                                                            [2020-02-26T11:19:04.432226000Z DEBUG quiche_client] done writing
                                                                                                                                                                            [2020-02-26T11:19:04.455884200Z DEBUG quiche_client] got 199 bytes
                                                                                                                                                                           [2020-02-26T11:19:04.456722300Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx pkt Initial version=ff000018 dcid=a90df470b71e1a33c9ed1658f23f5279c640c4b5 scid=b1f2ab74ade30afed34afa30acfca2ba8a4e6ca1 token= len=149 pn=0      
 [2020-02-26T11:19:04.457405500Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx frm ACK delay=199 blocks=[1..1]
                                                                                                                    [2020-02-26T11:19:04.457965100Z TRACE quiche::recovery] a90df470b71e1a33c9ed1658f23f5279c640c4b5 packet newly acked 1
                                                                                                                        [2020-02-26T11:19:04.458486700Z TRACE quiche::recovery] a90df470b71e1a33c9ed1658f23f5279c640c4b5 timer=none latest_rtt=27.1497ms srtt=Some(27.1497ms) min_rtt=27.1497ms rttvar=13.57485ms loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=14520 ssthresh=18446744073709551615 bytes_in_flight=0
                                                                                                                                                                                   [2020-02-26T11:19:04.459213900Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx frm CRYPTO off=0 len=122
                                                                                                                           [2020-02-26T11:19:04.460915900Z TRACE quiche::tls] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tls set encryption secret lvl=Handshake
                                                                                                          [2020-02-26T11:19:04.461694900Z DEBUG quiche_client] processed 199 bytes
                                                                                                                                                                     [2020-02-26T11:19:04.462244400Z DEBUG quiche_client] got 1196 bytes
                                                                                                                                                                          [2020-02-26T11:19:04.462787900Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx pkt Handshake version=ff000018 dcid=a90df470b71e1a33c9ed1658f23f5279c640c4b5 scid=b1f2ab74ade30afed34afa30acfca2ba8a4e6ca1 len=1147 pn=0           [2020-02-26T11:19:04.463518200Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx frm CRYPTO off=0 len=1126
                                                                                                                          [2020-02-26T11:19:04.464134900Z DEBUG quiche_client] processed 1196 bytes
                                                                                                                                                                    [2020-02-26T11:19:04.464708700Z DEBUG quiche_client] got 1197 bytes
                                                                                                                                                                          [2020-02-26T11:19:04.470842200Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx pkt Handshake version=ff000018 dcid=a90df470b71e1a33c9ed1658f23f5279c640c4b5 scid=b1f2ab74ade30afed34afa30acfca2ba8a4e6ca1 len=1148 pn=1           [2020-02-26T11:19:04.471979100Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx frm CRYPTO off=1126 len=1126
                                                                                                                       [2020-02-26T11:19:04.472918100Z DEBUG quiche_client] processed 1197 bytes
                                                                                                                                                                    [2020-02-26T11:19:04.473801700Z DEBUG quiche_client] got 740 bytes
                                                                                                                                                                           [2020-02-26T11:19:04.474625000Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx pkt Handshake version=ff000018 dcid=a90df470b71e1a33c9ed1658f23f5279c640c4b5 scid=b1f2ab74ade30afed34afa30acfca2ba8a4e6ca1 len=691 pn=2           
 [2020-02-26T11:19:04.475704800Z TRACE quiche] a90df470b71e1a33c9ed1658f23f5279c640c4b5 rx frm CRYPTO off=2252 len=669
                                                                                                                        [2020-02-26T11:19:04.479385100Z TRACE quiche::tls] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tls set encryption secret lvl=OneRTT
                                                                                                             [2020-02-26T11:19:04.484165000Z TRACE quiche::tls] a90df470b71e1a33c9ed1658f23f5279c640c4b5 tls write message lvl=Handshake len=36
                                                                                                           [2020-02-26T11:19:04.485172500Z ERROR quiche_client] recv failed: BufferTooShort                                                                                                                                                             thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TransportError(StreamLimit)', src/libcore/result.rs:1188:5                                                                                                           note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by piano-man** [comment]
It's working with the latest build !
