### ISSUE TITLE
quiche-client.rs: --dump-responses fails: Bad times: Is a directory (os error 21)

### ISSUE THREAD

**Issue by immohellwig** [cloudflare/quiche#386]
I tried to dump the responses into a directory as implied by --help. I dont think, that the error message is correct, since a directory is requested in manual.

Input:
RUST_BACKTRACE=full RUST_LOG=debug,trace cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-client https://quic.tech:4433 --dump-responses ./data

Output:
[2020-03-02T14:17:18.390803873Z TRACE mio::poll] registering with poller
[2020-03-02T14:17:18.419735828Z TRACE quiche::cc] Initializing congestion control: Reno
[2020-03-02T14:17:18.419973717Z INFO  quiche_client] connecting to 185.92.221.97:4433 from 10.170.152.56:58069 with scid 50a77f18965d6fc55b6f611de07c69463344e1aa
[2020-03-02T14:17:18.420189988Z TRACE quiche::tls] 50a77f18965d6fc55b6f611de07c69463344e1aa tls write message lvl=Initial len=512
[2020-03-02T14:17:18.420240035Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa tx pkt Initial version=babababa dcid=cd04f6877e14cf89649638a5e57763f5 scid=50a77f18965d6fc55b6f611de07c69463344e1aa len=1153 pn=0
[2020-03-02T14:17:18.420274912Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa tx frm CRYPTO off=0 len=512
[2020-03-02T14:17:18.420290672Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa tx frm PADDING len=621
[2020-03-02T14:17:18.420366500Z TRACE quiche::recovery] 50a77f18965d6fc55b6f611de07c69463344e1aa timer=999.632911ms latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=14520 ssthresh=18446744073709551615 bytes_in_flight=1200 
[2020-03-02T14:17:18.420441782Z DEBUG quiche_client] written 1200
[2020-03-02T14:17:18.444323628Z DEBUG quiche_client] got 55 bytes
[2020-03-02T14:17:18.444398143Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx pkt VersionNegotiation version=0 dcid=50a77f18965d6fc55b6f611de07c69463344e1aa scid=cd04f6877e14cf89649638a5e57763f5 versions=[ff00001b, ff000018, ff000017]
[2020-03-02T14:17:18.444503929Z DEBUG quiche_client] done reading
[2020-03-02T14:17:18.444710700Z TRACE quiche::tls] 50a77f18965d6fc55b6f611de07c69463344e1aa tls write message lvl=Initial len=512
[2020-03-02T14:17:18.444798502Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa tx pkt Initial version=ff00001b dcid=cd04f6877e14cf89649638a5e57763f5 scid=50a77f18965d6fc55b6f611de07c69463344e1aa len=1153 pn=1
[2020-03-02T14:17:18.444834722Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa tx frm CRYPTO off=0 len=512
[2020-03-02T14:17:18.444851243Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa tx frm PADDING len=621
[2020-03-02T14:17:18.444932738Z TRACE quiche::recovery] 50a77f18965d6fc55b6f611de07c69463344e1aa timer=999.579945ms latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=14520 ssthresh=18446744073709551615 bytes_in_flight=1200 
[2020-03-02T14:17:18.444995285Z DEBUG quiche_client] written 1200
[2020-03-02T14:17:18.445016567Z DEBUG quiche_client] done writing
[2020-03-02T14:17:18.470008331Z DEBUG quiche_client] got 199 bytes
[2020-03-02T14:17:18.470122539Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx pkt Initial version=ff00001b dcid=50a77f18965d6fc55b6f611de07c69463344e1aa scid=a4128b6e281fe0a418281688940e4e5ff9ff1ae8 token= len=149 pn=0
[2020-03-02T14:17:18.470220714Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx frm ACK delay=218 blocks=[1..1]
[2020-03-02T14:17:18.470289038Z TRACE quiche::recovery] 50a77f18965d6fc55b6f611de07c69463344e1aa packet newly acked 1
[2020-03-02T14:17:18.470319424Z TRACE quiche::recovery] 50a77f18965d6fc55b6f611de07c69463344e1aa timer=none latest_rtt=25.564123ms srtt=Some(25.564123ms) min_rtt=25.564123ms rttvar=12.782061ms loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=14520 ssthresh=18446744073709551615 bytes_in_flight=0 
[2020-03-02T14:17:18.470386168Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx frm CRYPTO off=0 len=122
[2020-03-02T14:17:18.471033224Z TRACE quiche::tls] 50a77f18965d6fc55b6f611de07c69463344e1aa tls set encryption secret lvl=Handshake
[2020-03-02T14:17:18.471167754Z DEBUG quiche_client] processed 199 bytes
[2020-03-02T14:17:18.471199361Z DEBUG quiche_client] got 1196 bytes
[2020-03-02T14:17:18.471229714Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx pkt Handshake version=ff00001b dcid=50a77f18965d6fc55b6f611de07c69463344e1aa scid=a4128b6e281fe0a418281688940e4e5ff9ff1ae8 len=1147 pn=0
[2020-03-02T14:17:18.471297086Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx frm CRYPTO off=0 len=1126
[2020-03-02T14:17:18.471360605Z DEBUG quiche_client] processed 1196 bytes
[2020-03-02T14:17:18.471389195Z DEBUG quiche_client] got 1197 bytes
[2020-03-02T14:17:18.471417552Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx pkt Handshake version=ff00001b dcid=50a77f18965d6fc55b6f611de07c69463344e1aa scid=a4128b6e281fe0a418281688940e4e5ff9ff1ae8 len=1148 pn=1
[2020-03-02T14:17:18.471482159Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx frm CRYPTO off=1126 len=1126
[2020-03-02T14:17:18.471539264Z DEBUG quiche_client] processed 1197 bytes
[2020-03-02T14:17:18.471566822Z DEBUG quiche_client] got 740 bytes
[2020-03-02T14:17:18.471596541Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx pkt Handshake version=ff00001b dcid=50a77f18965d6fc55b6f611de07c69463344e1aa scid=a4128b6e281fe0a418281688940e4e5ff9ff1ae8 len=691 pn=2
[2020-03-02T14:17:18.471660072Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa rx frm CRYPTO off=2252 len=669
[2020-03-02T14:17:18.472311731Z TRACE quiche::tls] 50a77f18965d6fc55b6f611de07c69463344e1aa tls set encryption secret lvl=OneRTT
[2020-03-02T14:17:18.472428992Z TRACE quiche::tls] 50a77f18965d6fc55b6f611de07c69463344e1aa tls write message lvl=Handshake len=36
[2020-03-02T14:17:18.472529470Z TRACE quiche] 50a77f18965d6fc55b6f611de07c69463344e1aa connection established: proto=Ok("h3-27") cipher=Some(AES128_GCM) curve=Some("X25519") sigalg=Some("rsa_pss_rsae_sha256") resumed=false TransportParams { original_connection_id: None, max_idle_timeout: 5000, stateless_reset_token: None, max_packet_size: 1350, initial_max_data: 10000000, initial_max_stream_data_bidi_local: 1000000, initial_max_stream_data_bidi_remote: 1000000, initial_max_stream_data_uni: 1000000, initial_max_streams_bidi: 100, initial_max_streams_uni: 100, ack_delay_exponent: 3, max_ack_delay: 25, disable_active_migration: true, active_conn_id_limit: 0 }
[2020-03-02T14:17:18.472624787Z DEBUG quiche_client] processed 740 bytes
[2020-03-02T14:17:18.472650757Z DEBUG quiche_client] recv() would block
[2020-03-02T14:17:18.472795235Z TRACE quiche::h3] 50a77f18965d6fc55b6f611de07c69463344e1aa open GREASE stream 14
[2020-03-02T14:17:18.472864738Z TRACE quiche::h3] 50a77f18965d6fc55b6f611de07c69463344e1aa tx frm GREASE stream=0
[2020-03-02T14:17:18.472938880Z TRACE quiche::h3] 50a77f18965d6fc55b6f611de07c69463344e1aa tx frm HEADERS stream=0 len=22 fin=true
[2020-03-02T14:17:18.472988301Z DEBUG quiche_apps] sending HTTP request [Header(":method", "GET"), Header(":scheme", "https"), Header(":authority", "quic.tech"), Header(":path", "/"), Header("user-agent", "quiche")]
thread 'main' panicked at 'Bad times: Is a directory (os error 21)', src/lib.rs:189:23
stack backtrace:
   0:     0x555a1f0b65c4 - backtrace::backtrace::libunwind::trace::he25250f78ba1020d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x555a1f0b65c4 - backtrace::backtrace::trace_unsynchronized::hd7e25f35da233a1e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x555a1f0b65c4 - std::sys_common::backtrace::_print_fmt::h5578a566a4c2ae4e
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x555a1f0b65c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4f87054ec86e936
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x555a1f0d1c2c - core::fmt::write::h393d55821fa8e2cb
                               at src/libcore/fmt/mod.rs:1025
   5:     0x555a1f0b2347 - std::io::Write::write_fmt::hc6645302c23e4504
                               at src/libstd/io/mod.rs:1426
   6:     0x555a1f0b863e - std::sys_common::backtrace::_print::he8a0a3ebec70e1d6
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x555a1f0b863e - std::sys_common::backtrace::print::hc2635fd6c7743ade
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x555a1f0b863e - std::panicking::default_hook::{{closure}}::h9849388798b72b2b
                               at src/libstd/panicking.rs:193
   9:     0x555a1f0b8331 - std::panicking::default_hook::h66e3afff11b02e47
                               at src/libstd/panicking.rs:210
  10:     0x555a1f0b8cbb - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
                               at src/libstd/panicking.rs:471
  11:     0x555a1f0b886e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x555a1f0b87b0 - std::panicking::begin_panic_fmt::h0ba4167e9ba9b09d
                               at src/libstd/panicking.rs:326
  13:     0x555a1eb78716 - quiche_apps::make_writer::hf488658985007b07
                               at src/lib.rs:189
  14:     0x555a1eb7f07b - <quiche_apps::Http3Conn as quiche_apps::HttpConn>::send_requests::h7f3242c1173ea00c
                               at src/lib.rs:701
  15:     0x555a1eb2d1a6 - quiche_client::main::h394a2e266c761a56
                               at src/bin/quiche-client.rs:270
  16:     0x555a1eb30b40 - std::rt::lang_start::{{closure}}::h738931699532aad5
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  17:     0x555a1f0b8703 - std::rt::lang_start_internal::{{closure}}::h4aedff5d9863b36b
                               at src/libstd/rt.rs:52
  18:     0x555a1f0b8703 - std::panicking::try::do_call::h0630fe3da32a089b
                               at src/libstd/panicking.rs:292
  19:     0x555a1f0bbc1a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  20:     0x555a1f0b9150 - std::panicking::try::hdfbe2fd873ac646c
                               at src/libstd/panicking.rs:270
  21:     0x555a1f0b9150 - std::panic::catch_unwind::hd7a9c10fa2bee1bc
                               at src/libstd/panic.rs:394
  22:     0x555a1f0b9150 - std::rt::lang_start_internal::hb8081e0e7e42ac0d
                               at src/libstd/rt.rs:51
  23:     0x555a1eb30b19 - std::rt::lang_start::h4a39e32cd378222e
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  24:     0x555a1eb2ea0a - main
  25:     0x7ff1aa5961e3 - __libc_start_main
  26:     0x555a1eb283ee - _start
  27:                0x0 - <unknown>

**Comment by LPardue** [comment]
The error in this case is because the path is `/` and there is no logical default mapping of this nameless resource into a filename. The error message is not very helpful in explaining this so I've opened a PR to add a bit more detail behind this failure.

The solution in this case is to request a resource such as `index.html`.
