### ISSUE TITLE
build error on win10 x86_64

### ISSUE THREAD

**Issue by wangwanchao** [cloudflare/quiche#634]
Run with `RUST_BACKTRACE=1 cargo build --examples` shows:
```
thread 'main' panicked at 'execution failed', C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:664:9
  stack backtrace:
     0: backtrace::backtrace::trace_unsynchronized
               at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
     1: std::sys_common::backtrace::_print_fmt
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78
     2: std::sys_common::backtrace::_print::{{impl}}::fmt
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:59
     3: core::fmt::write
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs:1076
     4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\mod.rs:1537
     5: std::sys_common::backtrace::_print
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62
     6: std::sys_common::backtrace::print
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:49
     7: std::panicking::default_hook::{{closure}}
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:198
     8: std::panicking::default_hook
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:217
     9: std::panicking::rust_panic_with_hook
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:526
    10: std::panicking::begin_panic<str*>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\panicking.rs:456
    11: build_script_build::run_command
               at .\build.rs:664
    12: build_script_build::compile
               at .\build.rs:532
    13: build_script_build::build_library::{{closure}}
               at .\build.rs:467
    14: core::ops::function::impls::{{impl}}::call_once<tuple<std::path::PathBuf*>,closure-1>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\ops\function.rs:286
    15: core::option::Option<std::path::PathBuf*>::map<std::path::PathBuf*,alloc::string::String,mut closure-1*>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\option.rs:453
    16: core::iter::adapters::{{impl}}::next<alloc::string::String,core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>,closure-1>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\iter\adapters\mod.rs:852
    17: alloc::vec::Vec<alloc::string::String>::extend_desugared<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\liballoc\vec.rs:2217
    18: alloc::vec::{{impl}}::spec_extend<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>, closure-1>>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\liballoc\vec.rs:2110
    19: alloc::vec::{{impl}}::from_iter<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>, closure-1>>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\liballoc\vec.rs:2105
    20: alloc::vec::{{impl}}::from_iter<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>, closure-1>>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\liballoc\vec.rs:1995
    21: core::iter::traits::iterator::Iterator::collect<core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>, closure-1>,alloc::vec::Vec
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\iter\traits\iterator.rs:1671
    22: build_script_build::build_library
               at .\build.rs:463
    23: build_script_build::build_c_code::{{closure}}
               at .\build.rs:436
    24: core::slice::{{impl}}::for_each<tuple<str*, slice<std::path::PathBuf>*, slice<std::path::PathBuf>*>,closure-4>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\slice\mod.rs:3607
    25: build_script_build::build_c_code
               at .\build.rs:435
    26: build_script_build::ring_build_rs_main
               at .\build.rs:298
    27: build_script_build::main
               at .\build.rs:255
    28: std::rt::lang_start::{{closure}}<tuple<>>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\rt.rs:67
    29: std::rt::lang_start_internal::{{closure}}
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:52
    30: std::panicking::try::do_call
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:348
    31: std::panicking::try
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:325
    32: std::panic::catch_unwind
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panic.rs:394
    33: std::rt::lang_start_internal
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:51
    34: std::rt::lang_start<tuple<>>
               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\rt.rs:67
    35: main
    36: invoke_main
               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:74
    37: __scrt_common_main_seh
               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264
    38: BaseThreadInitThunk
    39: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
then replace with `RUST_BACKTRACE=full cargo build --examples ` shows:
```
running "D:\\Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "include" "-W4" "/GS" "/Gy" "/EHsc" "/GR-" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Zc:rvalueCast" "/sdl" "/Wall" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/wd5045" "/Od" "/RTCsu" "-DNDEBUG" "-c" "/FoE:\\workspace\\OpenSource\\quiche\\target\\debug\\build\\ring-fce76a79dc6ea2af\\out\\montgomery.obj" "crypto/fipsmodule/bn/montgomery.c"
  thread 'main' panicked at 'execution failed', C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:664:9
  stack backtrace:
     0:     0x7ff76227d4be - backtrace::backtrace::trace_unsynchronized
                                 at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
     1:     0x7ff76227d4be - std::sys_common::backtrace::_print_fmt
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78
     2:     0x7ff76227d4be - std::sys_common::backtrace::_print::{{impl}}::fmt
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:59
     3:     0x7ff7622952ac - core::fmt::write
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs:1076
     4:     0x7ff762277df3 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\mod.rs:1537
     5:     0x7ff762280b7b - std::sys_common::backtrace::_print
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62
     6:     0x7ff762280b7b - std::sys_common::backtrace::print
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:49
     7:     0x7ff762280b7b - std::panicking::default_hook::{{closure}}
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:198
     8:     0x7ff7622807c8 - std::panicking::default_hook
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:217
     9:     0x7ff76228134f - std::panicking::rust_panic_with_hook
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:526
    10:     0x7ff76221ec12 - std::panicking::begin_panic<str*>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\panicking.rs:456
    11:     0x7ff7621d5bb3 - build_script_build::run_command
                                 at C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:664
    12:     0x7ff7621d482c - build_script_build::compile
                                 at C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:532
    13:     0x7ff7621d4289 - build_script_build::build_library::{{closure}}
                                 at C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:467
    14:     0x7ff7621d11d0 - core::ops::function::impls::{{impl}}::call_once<tuple<std::path::PathBuf*>,closure-1>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\ops\function.rs:286
    15:     0x7ff7621e4c4f - core::option::Option<std::path::PathBuf*>::map<std::path::PathBuf*,alloc::string::String,mut closure-1*>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\option.rs:453
    16:     0x7ff7621e16f8 - core::iter::adapters::{{impl}}::next<alloc::string::String,core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>,closure-1>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\iter\adapters\mod.rs:852
    17:     0x7ff7621d8795 - alloc::vec::Vec<alloc::string::String>::extend_desugared<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\liballoc\vec.rs:2217
    18:     0x7ff7621d988e - alloc::vec::{{impl}}::spec_extend<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>, closure-1>>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\liballoc\vec.rs:2110
    19:     0x7ff7621da1e7 - alloc::vec::{{impl}}::from_iter<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>, closure-1>>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\liballoc\vec.rs:2105
    20:     0x7ff7621db0c3 - alloc::vec::{{impl}}::from_iter<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>, closure-1>>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\liballoc\vec.rs:1995
    21:     0x7ff7621e06f1 - core::iter::traits::iterator::Iterator::collect<core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure-0>, closure-1>,alloc::vec::Vec
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\iter\traits\iterator.rs:1671
    22:     0x7ff7621d38df - build_script_build::build_library
                                 at C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:463
    23:     0x7ff7621d35c6 - build_script_build::build_c_code::{{closure}}
                                 at C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:436
    24:     0x7ff7621dfa2d - core::slice::{{impl}}::for_each<tuple<str*, slice<std::path::PathBuf>*, slice<std::path::PathBuf>*>,closure-4>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\slice\mod.rs:3607
    25:     0x7ff7621d2fe8 - build_script_build::build_c_code
                                 at C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:435
    26:     0x7ff7621d1c0c - build_script_build::ring_build_rs_main
                                 at C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:298
    27:     0x7ff7621d13e9 - build_script_build::main
                                 at C:\Users\GGGGe\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.15\build.rs:255
    28:     0x7ff7621dc8cb - std::rt::lang_start::{{closure}}<tuple<>>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\rt.rs:67
    29:     0x7ff762281546 - std::rt::lang_start_internal::{{closure}}
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:52
    30:     0x7ff762281546 - std::panicking::try::do_call
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:348
    31:     0x7ff762281546 - std::panicking::try
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:325
    32:     0x7ff762281546 - std::panic::catch_unwind
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panic.rs:394
    33:     0x7ff762281546 - std::rt::lang_start_internal
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:51
    34:     0x7ff7621dc8a3 - std::rt::lang_start<tuple<>>
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\rt.rs:67
    35:     0x7ff7621d7c80 - main
    36:     0x7ff76229a028 - invoke_main
                                 at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:74
    37:     0x7ff76229a028 - __scrt_common_main_seh
                                 at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264
    38:     0x7ffb16ad7bd4 - BaseThreadInitThunk
    39:     0x7ffb185ece51 - RtlUserThreadStart
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by LPardue** [comment]
Is this still a problem. Our CI builds Windows versions, so the failure indicates it could be a problem with your build environment or steps.

**Comment by LPardue** [comment]
Closing due to inactivity. Please reopen if there is more information.
