### ISSUE TITLE
cargo test failed

### ISSUE THREAD

**Issue by cute** [cloudflare/quiche#747]
```
rustc -V
rustc 1.48.0 (7eac88abb 2020-11-16)
```

```
    Blocking waiting for file lock on build directory
   Compiling quiche v0.6.0 (/Users/dev/quiche)
error: failed to run custom build command for `quiche v0.6.0 (/Users/dev/quiche)`

Caused by:
  process didn't exit successfully: `/Users/dev/quiche/target/debug/build/quiche-236c2f8ce5bffce3/build-script-build` (exit code: 101)
  --- stdout
  running: "cmake" "/Users/dev/quiche/deps/boringssl" "-DCMAKE_INSTALL_PREFIX=/Users/dev/quiche/target/debug/build/quiche-03629c2136def5f0/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- The ASM compiler identification is unknown
  -- Found assembler: /usr/bin/cc
  -- Warning: Did not find file Compiler/-ASM
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /Users/dev/quiche/target/debug/build/quiche-03629c2136def5f0/out/build
  running: "cmake" "--build" "." "--target" "bssl" "--config" "Debug" "--"
  [ 13%] Built target ssl
  [ 13%] Building ASM object CMakeFiles/crypto.dir/mac-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S.o
  [ 14%] Building ASM object CMakeFiles/crypto.dir/mac-x86_64/crypto/chacha/chacha-x86_64.S.o
  [ 14%] Building ASM object CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/aesni-gcm-x86_64.S.o
  [ 14%] Building ASM object CMakeFiles/crypto.dir/mac-x86_64/crypto/cipher_extra/aes128gcmsiv-x86_64.S.o
  [ 14%] Building ASM object CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/ghash-x86_64.S.o
  [ 16%] Building ASM object CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/aesni-x86_64.S.o
  [ 16%] Building ASM object CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/md5-x86_64.S.o
  [ 16%] Building ASM object CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/ghash-ssse3-x86_64.S.o

  --- stderr
  clang: error: unsupported argument '-g' to option 'Wa,'
  clang: error: unsupported argument '-g' to option 'Wa,'
  clang: error: unsupported argument '-g' to option 'Wa,'
  clang: error: unsupported argument '-g' to option 'Wa,'
  clang: error: unsupported argument '-g' to option 'Wa,'
  clang: error: unsupported argument '-g' to option 'Wa,'
  clang: error: unsupported argument '-g' to option 'Wa,'
  clang: error: unsupported argument '-g' to option 'Wa,'
  make[3]: *** [CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/ghash-ssse3-x86_64.S.o] Error 1
  make[3]: *** Waiting for unfinished jobs....
  make[3]: *** [CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/aesni-x86_64.S.o] Error 1
  make[3]: *** [CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/md5-x86_64.S.o] Error 1
  make[3]: *** [CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/ghash-x86_64.S.o] Error 1
  make[3]: *** [CMakeFiles/crypto.dir/mac-x86_64/crypto/chacha/chacha-x86_64.S.o] Error 1
  make[3]: *** [CMakeFiles/crypto.dir/mac-x86_64/crypto/cipher_extra/aes128gcmsiv-x86_64.S.o] Error 1
  make[3]: *** [CMakeFiles/crypto.dir/mac-x86_64/crypto/fipsmodule/aesni-gcm-x86_64.S.o] Error 1
  make[3]: *** [CMakeFiles/crypto.dir/mac-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S.o] Error 1
  make[2]: *** [CMakeFiles/crypto.dir/all] Error 2
  make[1]: *** [CMakeFiles/bssl.dir/rule] Error 2
  make: *** [bssl] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2

  build script failed, must exit now', /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
     1: std::panicking::begin_panic_fmt
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
     2: cmake::fail
               at /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894
     3: cmake::run
               at /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:872
     4: cmake::Config::build
               at /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:778
     5: build_script_build::main::{{closure}}
               at ./src/build.rs:241
     6: core::result::Result<T,E>::unwrap_or_else
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:825
     7: build_script_build::main
               at ./src/build.rs:233
     8: core::ops::function::FnOnce::call_once
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cute** [comment]
When I remove Wa,g, it is working.
